name: Build and Release .NET Application

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_desktop_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./out

      - name: Create zip of published output
        run: |
          Compress-Archive -Path ./out/* -DestinationPath ./out/published-app.zip

      - name: Upload published app to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./out/published-app.zip  # Path to the zipped file
          asset_name: PDFTableExtractor.zip  # The name for the asset in the release
          tag: ${{ github.ref }}  # Upload it under the tag that triggered the workflow
